package com.springmvc.entity;

import java.util.Date;

public class Birthcontrolinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String personalRecordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.couplepeers
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String couplepeers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.maritalprove
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String maritalprove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.maritalcartnum
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String maritalcartnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.insured
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String insured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.birthinfo
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String birthinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.birthboy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String birthboy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.birthgirl
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String birthgirl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.birthinpolicy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String birthinpolicy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.birthoutpolicy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String birthoutpolicy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.pregnancy_contraception_info
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String pregnancyContraceptionInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.measuretime
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date measuretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.birth_thisyear
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String birthThisyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.birthday
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.policy_inorout
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String policyInorout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column birthcontrolinfo.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String updatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.recordid
     *
     * @return the value of birthcontrolinfo.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.recordid
     *
     * @param recordid the value for birthcontrolinfo.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.personal_recordid
     *
     * @return the value of birthcontrolinfo.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getPersonalRecordid() {
        return personalRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.personal_recordid
     *
     * @param personalRecordid the value for birthcontrolinfo.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPersonalRecordid(String personalRecordid) {
        this.personalRecordid = personalRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.couplepeers
     *
     * @return the value of birthcontrolinfo.couplepeers
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCouplepeers() {
        return couplepeers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.couplepeers
     *
     * @param couplepeers the value for birthcontrolinfo.couplepeers
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCouplepeers(String couplepeers) {
        this.couplepeers = couplepeers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.maritalprove
     *
     * @return the value of birthcontrolinfo.maritalprove
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getMaritalprove() {
        return maritalprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.maritalprove
     *
     * @param maritalprove the value for birthcontrolinfo.maritalprove
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setMaritalprove(String maritalprove) {
        this.maritalprove = maritalprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.maritalcartnum
     *
     * @return the value of birthcontrolinfo.maritalcartnum
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getMaritalcartnum() {
        return maritalcartnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.maritalcartnum
     *
     * @param maritalcartnum the value for birthcontrolinfo.maritalcartnum
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setMaritalcartnum(String maritalcartnum) {
        this.maritalcartnum = maritalcartnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.insured
     *
     * @return the value of birthcontrolinfo.insured
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getInsured() {
        return insured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.insured
     *
     * @param insured the value for birthcontrolinfo.insured
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setInsured(String insured) {
        this.insured = insured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.birthinfo
     *
     * @return the value of birthcontrolinfo.birthinfo
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getBirthinfo() {
        return birthinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.birthinfo
     *
     * @param birthinfo the value for birthcontrolinfo.birthinfo
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setBirthinfo(String birthinfo) {
        this.birthinfo = birthinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.birthboy
     *
     * @return the value of birthcontrolinfo.birthboy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getBirthboy() {
        return birthboy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.birthboy
     *
     * @param birthboy the value for birthcontrolinfo.birthboy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setBirthboy(String birthboy) {
        this.birthboy = birthboy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.birthgirl
     *
     * @return the value of birthcontrolinfo.birthgirl
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getBirthgirl() {
        return birthgirl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.birthgirl
     *
     * @param birthgirl the value for birthcontrolinfo.birthgirl
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setBirthgirl(String birthgirl) {
        this.birthgirl = birthgirl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.birthinpolicy
     *
     * @return the value of birthcontrolinfo.birthinpolicy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getBirthinpolicy() {
        return birthinpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.birthinpolicy
     *
     * @param birthinpolicy the value for birthcontrolinfo.birthinpolicy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setBirthinpolicy(String birthinpolicy) {
        this.birthinpolicy = birthinpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.birthoutpolicy
     *
     * @return the value of birthcontrolinfo.birthoutpolicy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getBirthoutpolicy() {
        return birthoutpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.birthoutpolicy
     *
     * @param birthoutpolicy the value for birthcontrolinfo.birthoutpolicy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setBirthoutpolicy(String birthoutpolicy) {
        this.birthoutpolicy = birthoutpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.pregnancy_contraception_info
     *
     * @return the value of birthcontrolinfo.pregnancy_contraception_info
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getPregnancyContraceptionInfo() {
        return pregnancyContraceptionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.pregnancy_contraception_info
     *
     * @param pregnancyContraceptionInfo the value for birthcontrolinfo.pregnancy_contraception_info
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPregnancyContraceptionInfo(String pregnancyContraceptionInfo) {
        this.pregnancyContraceptionInfo = pregnancyContraceptionInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.measuretime
     *
     * @return the value of birthcontrolinfo.measuretime
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getMeasuretime() {
        return measuretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.measuretime
     *
     * @param measuretime the value for birthcontrolinfo.measuretime
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setMeasuretime(Date measuretime) {
        this.measuretime = measuretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.birth_thisyear
     *
     * @return the value of birthcontrolinfo.birth_thisyear
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getBirthThisyear() {
        return birthThisyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.birth_thisyear
     *
     * @param birthThisyear the value for birthcontrolinfo.birth_thisyear
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setBirthThisyear(String birthThisyear) {
        this.birthThisyear = birthThisyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.birthday
     *
     * @return the value of birthcontrolinfo.birthday
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.birthday
     *
     * @param birthday the value for birthcontrolinfo.birthday
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.policy_inorout
     *
     * @return the value of birthcontrolinfo.policy_inorout
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getPolicyInorout() {
        return policyInorout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.policy_inorout
     *
     * @param policyInorout the value for birthcontrolinfo.policy_inorout
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPolicyInorout(String policyInorout) {
        this.policyInorout = policyInorout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.create_time
     *
     * @return the value of birthcontrolinfo.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.create_time
     *
     * @param createTime the value for birthcontrolinfo.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.update_time
     *
     * @return the value of birthcontrolinfo.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.update_time
     *
     * @param updateTime the value for birthcontrolinfo.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.create_person
     *
     * @return the value of birthcontrolinfo.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.create_person
     *
     * @param createPerson the value for birthcontrolinfo.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column birthcontrolinfo.update_person
     *
     * @return the value of birthcontrolinfo.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column birthcontrolinfo.update_person
     *
     * @param updatePerson the value for birthcontrolinfo.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }
}