package com.springmvc.entity;

import java.util.Date;

public class DataTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.number
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.type
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.superiormumber
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String superiormumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_table.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String updatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.number
     *
     * @return the value of data_table.number
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.number
     *
     * @param number the value for data_table.number
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.name
     *
     * @return the value of data_table.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.name
     *
     * @param name the value for data_table.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.type
     *
     * @return the value of data_table.type
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.type
     *
     * @param type the value for data_table.type
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.superiormumber
     *
     * @return the value of data_table.superiormumber
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getSuperiormumber() {
        return superiormumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.superiormumber
     *
     * @param superiormumber the value for data_table.superiormumber
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setSuperiormumber(String superiormumber) {
        this.superiormumber = superiormumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.create_time
     *
     * @return the value of data_table.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.create_time
     *
     * @param createTime the value for data_table.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.update_time
     *
     * @return the value of data_table.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.update_time
     *
     * @param updateTime the value for data_table.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.create_person
     *
     * @return the value of data_table.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.create_person
     *
     * @param createPerson the value for data_table.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_table.update_person
     *
     * @return the value of data_table.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_table.update_person
     *
     * @param updatePerson the value for data_table.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }
}