package com.springmvc.entity;

import java.util.Date;

public class Employmentinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String personalRecordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.unit
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.unittype
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unittype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.unitlocation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unitlocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.unitlocation_city_country_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unitlocationCityCountryDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.unitlocation_town
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unitlocationTown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.unitlocation_village
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unitlocationVillage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.unitlocation_street
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unitlocationStreet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.unitlocation_Gatehousenum
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unitlocationGatehousenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.unitlocation_Gatehouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unitlocationGatehouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.organizationcode
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String organizationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.legalrepresentative
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String legalrepresentative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.laborcontract
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String laborcontract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.link_phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String linkPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.insured
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String insured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.unitsecurity_num
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unitsecurityNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.unit_num
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unitNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.industy_type
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String industyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.job_title
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String jobTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.jobskill_register
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String jobskillRegister;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.career
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String career;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employmentinfo.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String updatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.recordid
     *
     * @return the value of employmentinfo.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.recordid
     *
     * @param recordid the value for employmentinfo.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.personal_recordid
     *
     * @return the value of employmentinfo.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getPersonalRecordid() {
        return personalRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.personal_recordid
     *
     * @param personalRecordid the value for employmentinfo.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPersonalRecordid(String personalRecordid) {
        this.personalRecordid = personalRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.unit
     *
     * @return the value of employmentinfo.unit
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.unit
     *
     * @param unit the value for employmentinfo.unit
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.unittype
     *
     * @return the value of employmentinfo.unittype
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnittype() {
        return unittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.unittype
     *
     * @param unittype the value for employmentinfo.unittype
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnittype(String unittype) {
        this.unittype = unittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.unitlocation
     *
     * @return the value of employmentinfo.unitlocation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnitlocation() {
        return unitlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.unitlocation
     *
     * @param unitlocation the value for employmentinfo.unitlocation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnitlocation(String unitlocation) {
        this.unitlocation = unitlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.unitlocation_city_country_district
     *
     * @return the value of employmentinfo.unitlocation_city_country_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnitlocationCityCountryDistrict() {
        return unitlocationCityCountryDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.unitlocation_city_country_district
     *
     * @param unitlocationCityCountryDistrict the value for employmentinfo.unitlocation_city_country_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnitlocationCityCountryDistrict(String unitlocationCityCountryDistrict) {
        this.unitlocationCityCountryDistrict = unitlocationCityCountryDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.unitlocation_town
     *
     * @return the value of employmentinfo.unitlocation_town
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnitlocationTown() {
        return unitlocationTown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.unitlocation_town
     *
     * @param unitlocationTown the value for employmentinfo.unitlocation_town
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnitlocationTown(String unitlocationTown) {
        this.unitlocationTown = unitlocationTown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.unitlocation_village
     *
     * @return the value of employmentinfo.unitlocation_village
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnitlocationVillage() {
        return unitlocationVillage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.unitlocation_village
     *
     * @param unitlocationVillage the value for employmentinfo.unitlocation_village
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnitlocationVillage(String unitlocationVillage) {
        this.unitlocationVillage = unitlocationVillage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.unitlocation_street
     *
     * @return the value of employmentinfo.unitlocation_street
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnitlocationStreet() {
        return unitlocationStreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.unitlocation_street
     *
     * @param unitlocationStreet the value for employmentinfo.unitlocation_street
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnitlocationStreet(String unitlocationStreet) {
        this.unitlocationStreet = unitlocationStreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.unitlocation_Gatehousenum
     *
     * @return the value of employmentinfo.unitlocation_Gatehousenum
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnitlocationGatehousenum() {
        return unitlocationGatehousenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.unitlocation_Gatehousenum
     *
     * @param unitlocationGatehousenum the value for employmentinfo.unitlocation_Gatehousenum
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnitlocationGatehousenum(String unitlocationGatehousenum) {
        this.unitlocationGatehousenum = unitlocationGatehousenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.unitlocation_Gatehouse
     *
     * @return the value of employmentinfo.unitlocation_Gatehouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnitlocationGatehouse() {
        return unitlocationGatehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.unitlocation_Gatehouse
     *
     * @param unitlocationGatehouse the value for employmentinfo.unitlocation_Gatehouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnitlocationGatehouse(String unitlocationGatehouse) {
        this.unitlocationGatehouse = unitlocationGatehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.organizationcode
     *
     * @return the value of employmentinfo.organizationcode
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getOrganizationcode() {
        return organizationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.organizationcode
     *
     * @param organizationcode the value for employmentinfo.organizationcode
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setOrganizationcode(String organizationcode) {
        this.organizationcode = organizationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.legalrepresentative
     *
     * @return the value of employmentinfo.legalrepresentative
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getLegalrepresentative() {
        return legalrepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.legalrepresentative
     *
     * @param legalrepresentative the value for employmentinfo.legalrepresentative
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setLegalrepresentative(String legalrepresentative) {
        this.legalrepresentative = legalrepresentative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.laborcontract
     *
     * @return the value of employmentinfo.laborcontract
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getLaborcontract() {
        return laborcontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.laborcontract
     *
     * @param laborcontract the value for employmentinfo.laborcontract
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setLaborcontract(String laborcontract) {
        this.laborcontract = laborcontract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.link_phone
     *
     * @return the value of employmentinfo.link_phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getLinkPhone() {
        return linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.link_phone
     *
     * @param linkPhone the value for employmentinfo.link_phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setLinkPhone(String linkPhone) {
        this.linkPhone = linkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.insured
     *
     * @return the value of employmentinfo.insured
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getInsured() {
        return insured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.insured
     *
     * @param insured the value for employmentinfo.insured
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setInsured(String insured) {
        this.insured = insured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.unitsecurity_num
     *
     * @return the value of employmentinfo.unitsecurity_num
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnitsecurityNum() {
        return unitsecurityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.unitsecurity_num
     *
     * @param unitsecurityNum the value for employmentinfo.unitsecurity_num
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnitsecurityNum(String unitsecurityNum) {
        this.unitsecurityNum = unitsecurityNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.unit_num
     *
     * @return the value of employmentinfo.unit_num
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnitNum() {
        return unitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.unit_num
     *
     * @param unitNum the value for employmentinfo.unit_num
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnitNum(String unitNum) {
        this.unitNum = unitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.industy_type
     *
     * @return the value of employmentinfo.industy_type
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getIndustyType() {
        return industyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.industy_type
     *
     * @param industyType the value for employmentinfo.industy_type
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setIndustyType(String industyType) {
        this.industyType = industyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.job_title
     *
     * @return the value of employmentinfo.job_title
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.job_title
     *
     * @param jobTitle the value for employmentinfo.job_title
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.jobskill_register
     *
     * @return the value of employmentinfo.jobskill_register
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getJobskillRegister() {
        return jobskillRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.jobskill_register
     *
     * @param jobskillRegister the value for employmentinfo.jobskill_register
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setJobskillRegister(String jobskillRegister) {
        this.jobskillRegister = jobskillRegister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.career
     *
     * @return the value of employmentinfo.career
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCareer() {
        return career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.career
     *
     * @param career the value for employmentinfo.career
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCareer(String career) {
        this.career = career;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.create_time
     *
     * @return the value of employmentinfo.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.create_time
     *
     * @param createTime the value for employmentinfo.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.update_time
     *
     * @return the value of employmentinfo.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.update_time
     *
     * @param updateTime the value for employmentinfo.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.create_person
     *
     * @return the value of employmentinfo.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.create_person
     *
     * @param createPerson the value for employmentinfo.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employmentinfo.update_person
     *
     * @return the value of employmentinfo.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employmentinfo.update_person
     *
     * @param updatePerson the value for employmentinfo.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }
}