package com.springmvc.entity;

import java.util.Date;

public class FamilyMembers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String personalRecordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.relationship
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String relationship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.idcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.sex
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.birthday
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.vaccination_certificate
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String vaccinationCertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.school
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_members.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String updatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.recordid
     *
     * @return the value of family_members.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.recordid
     *
     * @param recordid the value for family_members.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.personal_recordid
     *
     * @return the value of family_members.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getPersonalRecordid() {
        return personalRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.personal_recordid
     *
     * @param personalRecordid the value for family_members.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPersonalRecordid(String personalRecordid) {
        this.personalRecordid = personalRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.relationship
     *
     * @return the value of family_members.relationship
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.relationship
     *
     * @param relationship the value for family_members.relationship
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.idcard
     *
     * @return the value of family_members.idcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.idcard
     *
     * @param idcard the value for family_members.idcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.name
     *
     * @return the value of family_members.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.name
     *
     * @param name the value for family_members.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.sex
     *
     * @return the value of family_members.sex
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.sex
     *
     * @param sex the value for family_members.sex
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.birthday
     *
     * @return the value of family_members.birthday
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.birthday
     *
     * @param birthday the value for family_members.birthday
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.vaccination_certificate
     *
     * @return the value of family_members.vaccination_certificate
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getVaccinationCertificate() {
        return vaccinationCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.vaccination_certificate
     *
     * @param vaccinationCertificate the value for family_members.vaccination_certificate
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setVaccinationCertificate(String vaccinationCertificate) {
        this.vaccinationCertificate = vaccinationCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.school
     *
     * @return the value of family_members.school
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.school
     *
     * @param school the value for family_members.school
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.create_time
     *
     * @return the value of family_members.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.create_time
     *
     * @param createTime the value for family_members.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.update_time
     *
     * @return the value of family_members.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.update_time
     *
     * @param updateTime the value for family_members.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.create_person
     *
     * @return the value of family_members.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.create_person
     *
     * @param createPerson the value for family_members.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_members.update_person
     *
     * @return the value of family_members.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column family_members.update_person
     *
     * @param updatePerson the value for family_members.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }
}