package com.springmvc.entity;

import java.util.Date;

public class Lease {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.nhabitation_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String nhabitationRecordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.andlordname
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String andlordname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.ontactnumberl
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String ontactnumberl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.hethersigned
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String hethersigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.dcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String dcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.gentname
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String gentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.ontactnumbera
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String ontactnumbera;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.esponsy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String esponsy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.gentidcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String gentidcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lease.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String updatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.recordid
     *
     * @return the value of lease.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.recordid
     *
     * @param recordid the value for lease.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.nhabitation_recordid
     *
     * @return the value of lease.nhabitation_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getNhabitationRecordid() {
        return nhabitationRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.nhabitation_recordid
     *
     * @param nhabitationRecordid the value for lease.nhabitation_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setNhabitationRecordid(String nhabitationRecordid) {
        this.nhabitationRecordid = nhabitationRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.andlordname
     *
     * @return the value of lease.andlordname
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAndlordname() {
        return andlordname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.andlordname
     *
     * @param andlordname the value for lease.andlordname
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAndlordname(String andlordname) {
        this.andlordname = andlordname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.ontactnumberl
     *
     * @return the value of lease.ontactnumberl
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getOntactnumberl() {
        return ontactnumberl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.ontactnumberl
     *
     * @param ontactnumberl the value for lease.ontactnumberl
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setOntactnumberl(String ontactnumberl) {
        this.ontactnumberl = ontactnumberl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.hethersigned
     *
     * @return the value of lease.hethersigned
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getHethersigned() {
        return hethersigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.hethersigned
     *
     * @param hethersigned the value for lease.hethersigned
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setHethersigned(String hethersigned) {
        this.hethersigned = hethersigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.dcard
     *
     * @return the value of lease.dcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getDcard() {
        return dcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.dcard
     *
     * @param dcard the value for lease.dcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setDcard(String dcard) {
        this.dcard = dcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.gentname
     *
     * @return the value of lease.gentname
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getGentname() {
        return gentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.gentname
     *
     * @param gentname the value for lease.gentname
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setGentname(String gentname) {
        this.gentname = gentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.ontactnumbera
     *
     * @return the value of lease.ontactnumbera
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getOntactnumbera() {
        return ontactnumbera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.ontactnumbera
     *
     * @param ontactnumbera the value for lease.ontactnumbera
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setOntactnumbera(String ontactnumbera) {
        this.ontactnumbera = ontactnumbera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.esponsy
     *
     * @return the value of lease.esponsy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getEsponsy() {
        return esponsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.esponsy
     *
     * @param esponsy the value for lease.esponsy
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setEsponsy(String esponsy) {
        this.esponsy = esponsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.gentidcard
     *
     * @return the value of lease.gentidcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getGentidcard() {
        return gentidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.gentidcard
     *
     * @param gentidcard the value for lease.gentidcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setGentidcard(String gentidcard) {
        this.gentidcard = gentidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.create_time
     *
     * @return the value of lease.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.create_time
     *
     * @param createTime the value for lease.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.update_time
     *
     * @return the value of lease.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.update_time
     *
     * @param updateTime the value for lease.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.create_person
     *
     * @return the value of lease.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.create_person
     *
     * @param createPerson the value for lease.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lease.update_person
     *
     * @return the value of lease.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lease.update_person
     *
     * @param updatePerson the value for lease.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }
}