package com.springmvc.entity;

import java.util.Date;

public class LivingInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String personalRecordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.wayofresidence
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String wayofresidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.causeofresidence
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String causeofresidence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.housecategory
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String housecategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.addresscity
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String addresscity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.addresscounty
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String addresscounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.addressarea
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String addressarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.addressstreet
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String addressstreet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.addresscommunity
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String addresscommunity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.addressdetails
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String addressdetails;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.roomnumber
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String roomnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.typeofhouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String typeofhouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.houseuse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String houseuse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.inforcollector
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String inforcollector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.localpolicestation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String localpolicestation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column living_information.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String updatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.recordid
     *
     * @return the value of living_information.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.recordid
     *
     * @param recordid the value for living_information.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.personal_recordid
     *
     * @return the value of living_information.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getPersonalRecordid() {
        return personalRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.personal_recordid
     *
     * @param personalRecordid the value for living_information.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPersonalRecordid(String personalRecordid) {
        this.personalRecordid = personalRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.wayofresidence
     *
     * @return the value of living_information.wayofresidence
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getWayofresidence() {
        return wayofresidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.wayofresidence
     *
     * @param wayofresidence the value for living_information.wayofresidence
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setWayofresidence(String wayofresidence) {
        this.wayofresidence = wayofresidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.causeofresidence
     *
     * @return the value of living_information.causeofresidence
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCauseofresidence() {
        return causeofresidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.causeofresidence
     *
     * @param causeofresidence the value for living_information.causeofresidence
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCauseofresidence(String causeofresidence) {
        this.causeofresidence = causeofresidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.housecategory
     *
     * @return the value of living_information.housecategory
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getHousecategory() {
        return housecategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.housecategory
     *
     * @param housecategory the value for living_information.housecategory
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setHousecategory(String housecategory) {
        this.housecategory = housecategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.addresscity
     *
     * @return the value of living_information.addresscity
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAddresscity() {
        return addresscity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.addresscity
     *
     * @param addresscity the value for living_information.addresscity
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAddresscity(String addresscity) {
        this.addresscity = addresscity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.addresscounty
     *
     * @return the value of living_information.addresscounty
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAddresscounty() {
        return addresscounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.addresscounty
     *
     * @param addresscounty the value for living_information.addresscounty
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAddresscounty(String addresscounty) {
        this.addresscounty = addresscounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.addressarea
     *
     * @return the value of living_information.addressarea
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAddressarea() {
        return addressarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.addressarea
     *
     * @param addressarea the value for living_information.addressarea
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAddressarea(String addressarea) {
        this.addressarea = addressarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.addressstreet
     *
     * @return the value of living_information.addressstreet
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAddressstreet() {
        return addressstreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.addressstreet
     *
     * @param addressstreet the value for living_information.addressstreet
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAddressstreet(String addressstreet) {
        this.addressstreet = addressstreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.addresscommunity
     *
     * @return the value of living_information.addresscommunity
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAddresscommunity() {
        return addresscommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.addresscommunity
     *
     * @param addresscommunity the value for living_information.addresscommunity
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAddresscommunity(String addresscommunity) {
        this.addresscommunity = addresscommunity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.addressdetails
     *
     * @return the value of living_information.addressdetails
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAddressdetails() {
        return addressdetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.addressdetails
     *
     * @param addressdetails the value for living_information.addressdetails
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAddressdetails(String addressdetails) {
        this.addressdetails = addressdetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.roomnumber
     *
     * @return the value of living_information.roomnumber
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.roomnumber
     *
     * @param roomnumber the value for living_information.roomnumber
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.typeofhouse
     *
     * @return the value of living_information.typeofhouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getTypeofhouse() {
        return typeofhouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.typeofhouse
     *
     * @param typeofhouse the value for living_information.typeofhouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setTypeofhouse(String typeofhouse) {
        this.typeofhouse = typeofhouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.houseuse
     *
     * @return the value of living_information.houseuse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getHouseuse() {
        return houseuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.houseuse
     *
     * @param houseuse the value for living_information.houseuse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setHouseuse(String houseuse) {
        this.houseuse = houseuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.inforcollector
     *
     * @return the value of living_information.inforcollector
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getInforcollector() {
        return inforcollector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.inforcollector
     *
     * @param inforcollector the value for living_information.inforcollector
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setInforcollector(String inforcollector) {
        this.inforcollector = inforcollector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.localpolicestation
     *
     * @return the value of living_information.localpolicestation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getLocalpolicestation() {
        return localpolicestation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.localpolicestation
     *
     * @param localpolicestation the value for living_information.localpolicestation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setLocalpolicestation(String localpolicestation) {
        this.localpolicestation = localpolicestation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.create_time
     *
     * @return the value of living_information.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.create_time
     *
     * @param createTime the value for living_information.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.update_time
     *
     * @return the value of living_information.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.update_time
     *
     * @param updateTime the value for living_information.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.create_person
     *
     * @return the value of living_information.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.create_person
     *
     * @param createPerson the value for living_information.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column living_information.update_person
     *
     * @return the value of living_information.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column living_information.update_person
     *
     * @param updatePerson the value for living_information.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }
}