package com.springmvc.entity;

import java.util.Date;

public class Personal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.formername
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String formername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.sex
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.cometime
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date cometime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.idcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.nation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.address
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.address_province
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String addressProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.address_city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String addressCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.address_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String addressDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.currentaddress
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.currentaddress_province
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddressProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.currentaddress_city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddressCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.currentaddress_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddressDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.currentaddress_Gatehouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddressGatehouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.telephone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.linkman
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.linkman__telephone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String linkmanTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.linkman_phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String linkmanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.educational
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String educational;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.politicalstatus
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String politicalstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.faith
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String faith;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.stature
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Integer stature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.weight
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.bloodtype
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String bloodtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.health
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String health;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.disability
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Integer disability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.workingconditions
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String workingconditions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.maritalstatus
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String maritalstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.imgurl
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.status
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.reason
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String updatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.recordid
     *
     * @return the value of personal.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.recordid
     *
     * @param recordid the value for personal.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.name
     *
     * @return the value of personal.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.name
     *
     * @param name the value for personal.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.formername
     *
     * @return the value of personal.formername
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getFormername() {
        return formername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.formername
     *
     * @param formername the value for personal.formername
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setFormername(String formername) {
        this.formername = formername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.sex
     *
     * @return the value of personal.sex
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.sex
     *
     * @param sex the value for personal.sex
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.cometime
     *
     * @return the value of personal.cometime
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getCometime() {
        return cometime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.cometime
     *
     * @param cometime the value for personal.cometime
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCometime(Date cometime) {
        this.cometime = cometime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.idcard
     *
     * @return the value of personal.idcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.idcard
     *
     * @param idcard the value for personal.idcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.nation
     *
     * @return the value of personal.nation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.nation
     *
     * @param nation the value for personal.nation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.address
     *
     * @return the value of personal.address
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.address
     *
     * @param address the value for personal.address
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.address_province
     *
     * @return the value of personal.address_province
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAddressProvince() {
        return addressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.address_province
     *
     * @param addressProvince the value for personal.address_province
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAddressProvince(String addressProvince) {
        this.addressProvince = addressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.address_city
     *
     * @return the value of personal.address_city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAddressCity() {
        return addressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.address_city
     *
     * @param addressCity the value for personal.address_city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.address_district
     *
     * @return the value of personal.address_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAddressDistrict() {
        return addressDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.address_district
     *
     * @param addressDistrict the value for personal.address_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAddressDistrict(String addressDistrict) {
        this.addressDistrict = addressDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.currentaddress
     *
     * @return the value of personal.currentaddress
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddress() {
        return currentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.currentaddress
     *
     * @param currentaddress the value for personal.currentaddress
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddress(String currentaddress) {
        this.currentaddress = currentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.currentaddress_province
     *
     * @return the value of personal.currentaddress_province
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddressProvince() {
        return currentaddressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.currentaddress_province
     *
     * @param currentaddressProvince the value for personal.currentaddress_province
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddressProvince(String currentaddressProvince) {
        this.currentaddressProvince = currentaddressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.currentaddress_city
     *
     * @return the value of personal.currentaddress_city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddressCity() {
        return currentaddressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.currentaddress_city
     *
     * @param currentaddressCity the value for personal.currentaddress_city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddressCity(String currentaddressCity) {
        this.currentaddressCity = currentaddressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.currentaddress_district
     *
     * @return the value of personal.currentaddress_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddressDistrict() {
        return currentaddressDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.currentaddress_district
     *
     * @param currentaddressDistrict the value for personal.currentaddress_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddressDistrict(String currentaddressDistrict) {
        this.currentaddressDistrict = currentaddressDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.currentaddress_Gatehouse
     *
     * @return the value of personal.currentaddress_Gatehouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddressGatehouse() {
        return currentaddressGatehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.currentaddress_Gatehouse
     *
     * @param currentaddressGatehouse the value for personal.currentaddress_Gatehouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddressGatehouse(String currentaddressGatehouse) {
        this.currentaddressGatehouse = currentaddressGatehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.phone
     *
     * @return the value of personal.phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.phone
     *
     * @param phone the value for personal.phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.telephone
     *
     * @return the value of personal.telephone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.telephone
     *
     * @param telephone the value for personal.telephone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.linkman
     *
     * @return the value of personal.linkman
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.linkman
     *
     * @param linkman the value for personal.linkman
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.linkman__telephone
     *
     * @return the value of personal.linkman__telephone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getLinkmanTelephone() {
        return linkmanTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.linkman__telephone
     *
     * @param linkmanTelephone the value for personal.linkman__telephone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setLinkmanTelephone(String linkmanTelephone) {
        this.linkmanTelephone = linkmanTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.linkman_phone
     *
     * @return the value of personal.linkman_phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getLinkmanPhone() {
        return linkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.linkman_phone
     *
     * @param linkmanPhone the value for personal.linkman_phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setLinkmanPhone(String linkmanPhone) {
        this.linkmanPhone = linkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.educational
     *
     * @return the value of personal.educational
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getEducational() {
        return educational;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.educational
     *
     * @param educational the value for personal.educational
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setEducational(String educational) {
        this.educational = educational;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.politicalstatus
     *
     * @return the value of personal.politicalstatus
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getPoliticalstatus() {
        return politicalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.politicalstatus
     *
     * @param politicalstatus the value for personal.politicalstatus
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPoliticalstatus(String politicalstatus) {
        this.politicalstatus = politicalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.faith
     *
     * @return the value of personal.faith
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getFaith() {
        return faith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.faith
     *
     * @param faith the value for personal.faith
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setFaith(String faith) {
        this.faith = faith;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.stature
     *
     * @return the value of personal.stature
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Integer getStature() {
        return stature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.stature
     *
     * @param stature the value for personal.stature
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setStature(Integer stature) {
        this.stature = stature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.weight
     *
     * @return the value of personal.weight
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.weight
     *
     * @param weight the value for personal.weight
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.bloodtype
     *
     * @return the value of personal.bloodtype
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getBloodtype() {
        return bloodtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.bloodtype
     *
     * @param bloodtype the value for personal.bloodtype
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setBloodtype(String bloodtype) {
        this.bloodtype = bloodtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.health
     *
     * @return the value of personal.health
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.health
     *
     * @param health the value for personal.health
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setHealth(String health) {
        this.health = health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.disability
     *
     * @return the value of personal.disability
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Integer getDisability() {
        return disability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.disability
     *
     * @param disability the value for personal.disability
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setDisability(Integer disability) {
        this.disability = disability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.workingconditions
     *
     * @return the value of personal.workingconditions
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getWorkingconditions() {
        return workingconditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.workingconditions
     *
     * @param workingconditions the value for personal.workingconditions
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setWorkingconditions(String workingconditions) {
        this.workingconditions = workingconditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.maritalstatus
     *
     * @return the value of personal.maritalstatus
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getMaritalstatus() {
        return maritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.maritalstatus
     *
     * @param maritalstatus the value for personal.maritalstatus
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.imgurl
     *
     * @return the value of personal.imgurl
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.imgurl
     *
     * @param imgurl the value for personal.imgurl
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.status
     *
     * @return the value of personal.status
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.status
     *
     * @param status the value for personal.status
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.reason
     *
     * @return the value of personal.reason
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.reason
     *
     * @param reason the value for personal.reason
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.create_time
     *
     * @return the value of personal.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.create_time
     *
     * @param createTime the value for personal.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.update_time
     *
     * @return the value of personal.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.update_time
     *
     * @param updateTime the value for personal.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.create_person
     *
     * @return the value of personal.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.create_person
     *
     * @param createPerson the value for personal.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.update_person
     *
     * @return the value of personal.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.update_person
     *
     * @param updatePerson the value for personal.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }
}