package com.springmvc.entity;

import java.util.Date;

public class SpouseInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String personalRecordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.idcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.currentaddress
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.currentaddress_province
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddressProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.currentaddress_city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddressCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.currentaddress_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddressDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.currentaddress_town
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddressTown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.currentaddress_village
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddressVillage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.currentaddress_Gatehouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String currentaddressGatehouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.workingconditions
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String workingconditions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.workunit
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String workunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Integer phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spouse_information.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String updatePerson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.recordid
     *
     * @return the value of spouse_information.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.recordid
     *
     * @param recordid the value for spouse_information.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.personal_recordid
     *
     * @return the value of spouse_information.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getPersonalRecordid() {
        return personalRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.personal_recordid
     *
     * @param personalRecordid the value for spouse_information.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPersonalRecordid(String personalRecordid) {
        this.personalRecordid = personalRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.name
     *
     * @return the value of spouse_information.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.name
     *
     * @param name the value for spouse_information.name
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.idcard
     *
     * @return the value of spouse_information.idcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.idcard
     *
     * @param idcard the value for spouse_information.idcard
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.currentaddress
     *
     * @return the value of spouse_information.currentaddress
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddress() {
        return currentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.currentaddress
     *
     * @param currentaddress the value for spouse_information.currentaddress
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddress(String currentaddress) {
        this.currentaddress = currentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.currentaddress_province
     *
     * @return the value of spouse_information.currentaddress_province
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddressProvince() {
        return currentaddressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.currentaddress_province
     *
     * @param currentaddressProvince the value for spouse_information.currentaddress_province
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddressProvince(String currentaddressProvince) {
        this.currentaddressProvince = currentaddressProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.currentaddress_city
     *
     * @return the value of spouse_information.currentaddress_city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddressCity() {
        return currentaddressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.currentaddress_city
     *
     * @param currentaddressCity the value for spouse_information.currentaddress_city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddressCity(String currentaddressCity) {
        this.currentaddressCity = currentaddressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.currentaddress_district
     *
     * @return the value of spouse_information.currentaddress_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddressDistrict() {
        return currentaddressDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.currentaddress_district
     *
     * @param currentaddressDistrict the value for spouse_information.currentaddress_district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddressDistrict(String currentaddressDistrict) {
        this.currentaddressDistrict = currentaddressDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.currentaddress_town
     *
     * @return the value of spouse_information.currentaddress_town
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddressTown() {
        return currentaddressTown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.currentaddress_town
     *
     * @param currentaddressTown the value for spouse_information.currentaddress_town
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddressTown(String currentaddressTown) {
        this.currentaddressTown = currentaddressTown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.currentaddress_village
     *
     * @return the value of spouse_information.currentaddress_village
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddressVillage() {
        return currentaddressVillage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.currentaddress_village
     *
     * @param currentaddressVillage the value for spouse_information.currentaddress_village
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddressVillage(String currentaddressVillage) {
        this.currentaddressVillage = currentaddressVillage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.currentaddress_Gatehouse
     *
     * @return the value of spouse_information.currentaddress_Gatehouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCurrentaddressGatehouse() {
        return currentaddressGatehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.currentaddress_Gatehouse
     *
     * @param currentaddressGatehouse the value for spouse_information.currentaddress_Gatehouse
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCurrentaddressGatehouse(String currentaddressGatehouse) {
        this.currentaddressGatehouse = currentaddressGatehouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.workingconditions
     *
     * @return the value of spouse_information.workingconditions
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getWorkingconditions() {
        return workingconditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.workingconditions
     *
     * @param workingconditions the value for spouse_information.workingconditions
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setWorkingconditions(String workingconditions) {
        this.workingconditions = workingconditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.workunit
     *
     * @return the value of spouse_information.workunit
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getWorkunit() {
        return workunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.workunit
     *
     * @param workunit the value for spouse_information.workunit
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setWorkunit(String workunit) {
        this.workunit = workunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.phone
     *
     * @return the value of spouse_information.phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.phone
     *
     * @param phone the value for spouse_information.phone
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.create_time
     *
     * @return the value of spouse_information.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.create_time
     *
     * @param createTime the value for spouse_information.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.update_time
     *
     * @return the value of spouse_information.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.update_time
     *
     * @param updateTime the value for spouse_information.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.create_person
     *
     * @return the value of spouse_information.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.create_person
     *
     * @param createPerson the value for spouse_information.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spouse_information.update_person
     *
     * @return the value of spouse_information.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spouse_information.update_person
     *
     * @param updatePerson the value for spouse_information.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }
}