package com.springmvc.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.unitname
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String unitname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.location
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.localpolicestation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String localpolicestation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.registerstate
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String registerstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.town
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String town;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.rolestate
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String rolestate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String updatePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    private String personalRecordid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.recordid
     *
     * @return the value of user.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.recordid
     *
     * @param recordid the value for user.recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account
     *
     * @return the value of user.account
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account
     *
     * @param account the value for user.account
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.unitname
     *
     * @return the value of user.unitname
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUnitname() {
        return unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.unitname
     *
     * @param unitname the value for user.unitname
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.location
     *
     * @return the value of user.location
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.location
     *
     * @param location the value for user.location
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.localpolicestation
     *
     * @return the value of user.localpolicestation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getLocalpolicestation() {
        return localpolicestation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.localpolicestation
     *
     * @param localpolicestation the value for user.localpolicestation
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setLocalpolicestation(String localpolicestation) {
        this.localpolicestation = localpolicestation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.district
     *
     * @return the value of user.district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.district
     *
     * @param district the value for user.district
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.registerstate
     *
     * @return the value of user.registerstate
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRegisterstate() {
        return registerstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.registerstate
     *
     * @param registerstate the value for user.registerstate
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRegisterstate(String registerstate) {
        this.registerstate = registerstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.town
     *
     * @return the value of user.town
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.town
     *
     * @param town the value for user.town
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setTown(String town) {
        this.town = town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.rolestate
     *
     * @return the value of user.rolestate
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getRolestate() {
        return rolestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.rolestate
     *
     * @param rolestate the value for user.rolestate
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setRolestate(String rolestate) {
        this.rolestate = rolestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_time
     *
     * @return the value of user.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_time
     *
     * @param updateTime the value for user.update_time
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_person
     *
     * @return the value of user.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_person
     *
     * @param createPerson the value for user.create_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.update_person
     *
     * @return the value of user.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getUpdatePerson() {
        return updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.update_person
     *
     * @param updatePerson the value for user.update_person
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setUpdatePerson(String updatePerson) {
        this.updatePerson = updatePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.personal_recordid
     *
     * @return the value of user.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public String getPersonalRecordid() {
        return personalRecordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.personal_recordid
     *
     * @param personalRecordid the value for user.personal_recordid
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    public void setPersonalRecordid(String personalRecordid) {
        this.personalRecordid = personalRecordid;
    }
}