package com.springmvc.dao;

import com.springmvc.entity.DataTable;

public interface DataTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int deleteByPrimaryKey(Integer number);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int insert(DataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int insertSelective(DataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    DataTable selectByPrimaryKey(Integer number);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int updateByPrimaryKeySelective(DataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_table
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int updateByPrimaryKey(DataTable record);
}