package com.springmvc.dao;

import com.springmvc.entity.FamilyMembers;

public interface FamilyMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int deleteByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int insert(FamilyMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int insertSelective(FamilyMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    FamilyMembers selectByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int updateByPrimaryKeySelective(FamilyMembers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_members
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int updateByPrimaryKey(FamilyMembers record);
}