package com.springmvc.dao;

import com.springmvc.entity.Lease;

public interface LeaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lease
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int deleteByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lease
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int insert(Lease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lease
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int insertSelective(Lease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lease
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    Lease selectByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lease
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int updateByPrimaryKeySelective(Lease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lease
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int updateByPrimaryKey(Lease record);
}