package com.springmvc.dao;

import com.springmvc.entity.Personal;

public interface PersonalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int deleteByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int insert(Personal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int insertSelective(Personal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    Personal selectByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int updateByPrimaryKeySelective(Personal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int updateByPrimaryKey(Personal record);
}