package com.springmvc.dao;

import com.springmvc.entity.SpouseInformation;

public interface SpouseInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spouse_information
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int deleteByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spouse_information
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int insert(SpouseInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spouse_information
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int insertSelective(SpouseInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spouse_information
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    SpouseInformation selectByPrimaryKey(String recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spouse_information
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int updateByPrimaryKeySelective(SpouseInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spouse_information
     *
     * @mbggenerated Tue Jul 16 17:55:42 CST 2019
     */
    int updateByPrimaryKey(SpouseInformation record);
}